# Generated by Django 4.2.4 on 2023-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='view_count'),
        ),
    ]
